title = "BLOCKCHAIN CONFIG"

[Network]
    Type="channel"
    CAFile="assets/sdk_ca/ca.crt"
    Cert="assets/sdk_ca/sdk.crt"
    Key="assets/sdk_ca/sdk.key"
    NodeURL=""

#    RpcNodeURL="http://10.100.244.100:1234/rpc/v0"
    RpcNodeURL="http://10.7.1.8:1234/rpc/v0"
    GroupID=1

[Account]
    KeyFile="assets/contract/*.pem"

[Chain]
    ChainID=1
    SMCrypto=false

[Contract]
    Address=""

